languageCode = "en-us"
title = "roobr3: carrier lost"
baseURL = "https://carrierlost.roobre.es/"

theme = "terminal"

[params]
  description = "Netsec and stuff" # Suggested, controls default description meta
  author = "Roberto \"Roobre\" Santalla (@rsroobre)" # Optional, controls author name display on posts
  contentTypeName = "post"
  fullWidthTheme = false
  centerTheme = true
  themeColor = "green"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "rsroobre"
  site = "https://github.com/roobre"

[params.logo]
  logoText = "roobr3: carrier lost"

[author]
  name = "Roberto \"Roobre\" Santalla (@rsroobre)"
  email = "roobre (@t) roobre d0t es"

SectionPagesMenu = "main"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About me @ Keybase"
  weight = 9
  identifier = "aboutme"
  url = "https://keybase.io/roobre"
