name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Build & publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build -t roobre/carrierlost .
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Upload docker images
        run: |
          docker push roobre/carrierlost
